language:
  it:
    languageCode: it
    contentDir: content
    title: "Dott.ssa Vincenza Castronovo"
    params:
      description: "Psicologa specializzata in disturbi del sonno e CBT-I"
  en:
    languageCode: en
    contentDir: content
    title: "Dr. Vincenza Castronovo"
    params:
      description: "Clinical psychologist specialized in sleep disorders and CBT-I"
