# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: Psychologist
    org_name: "Dott.ssa Vincenza Castronovo"
    description: "Psicologa clinica specializzata in disturbi del sonno e CBT-I"
    twitter: ''
  analytics:
    google_analytics: ''
  verification:
    google: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "Vincenza Castronovo"
      filename: "logo.svg"
    button:
      enable: false
    show_search: false
    show_theme_chooser: false

# Main navigation menu
main_menu:
  - name: Home
    url: /
    weight: 1
  - name: CBT-I
    url: /cbti/
    weight: 2
  - name: Contattami
    url: /contatti/
    weight: 3

# Site footer
footer:
  copyright:
    notice: "© {year} Dott.ssa Vincenza Castronovo"

# Localization and language support
defaultContentLanguage: it
languages:
  it:
    languageName: Italiano
    weight: 1
  en:
    languageName: English
    weight: 2

# Locale formats
locale:
  date_format: '02/01/2006'
  time_format: '15:04'
